server:
  port: 8000

spring:
  application:
    name: books-service
  
  datasource:
    url: ${POSTGRESBD_URL}
    username: ${POSTGRESBD_USERNAME}
    password: ${POSTGRESBD_PASSWORD}
    driver-class-name: org.postgresql.Driver

  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      mapping: /graphiql
      enabled: true

  jpa:
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
