/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pr1;

public class App {

    public static void main(String[] args) {
        Printer mess = new Printer();

        Thread thread1 = new Thread(mess);
        thread1.setName("Ping");
        thread1.start();

        Thread thread2 = new Thread(mess);
        thread2.setName("Pong");
        thread2.start();
    }

    static class Printer implements Runnable {
        @Override
        public void run() {
            synchronized(this) {
                for(;;) {
                    try {
                        notify();
                        System.out.println(Thread.currentThread().getName());
                        wait();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }
}
